"use client";

import { useCallback, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import type { SharedCard } from "./types";

type Person={email:string;displayName:string;avatarUrl:string|null;relationship:"none"|"incoming"|"outgoing"|"friend";lastActiveAt?:number|null};
type Friend=Person&{cards:SharedCard[]};
type Trade={id:string;direction:"incoming"|"outgoing";otherEmail:string;otherName:string;otherAvatarUrl:string|null;status:"pending"|"accepted"|"declined"|"cancelled";createdAt:number;offeredCard:SharedCard|null;requestedCard:SharedCard|null};
type SocialData={ownFriendId:string;people:Person[];friends:Friend[];trades:Trade[]};

function MiniCard({card,selected,onClick}:{card:SharedCard;selected?:boolean;onClick?:()=>void}){const body=<><i>{selected?"✓":""}</i><img src={card.imageUrl} alt={`${card.name}のカード`} loading="lazy" decoding="async"/><span><strong>{card.name}</strong><small>{card.rarity} · {card.team||card.country}</small></span></>;return onClick?<button type="button" className={`social-card ${selected?"is-selected":""}`} onClick={onClick}>{body}</button>:<div className="social-card">{body}</div>}
function PersonAvatar({person}:{person:{displayName:string;avatarUrl:string|null}}){return person.avatarUrl?<img className="person-avatar" src={person.avatarUrl} alt=""/>:<div className="person-avatar">{person.displayName.slice(0,1)}</div>}
function FriendRow({friend,onOpen}:{friend:Friend;onOpen:()=>void}){return <button type="button" className="native-friend-row" onClick={onOpen}><PersonAvatar person={friend}/><span><strong>{friend.displayName}</strong><small>{friend.cards.length} cards</small></span><b>›</b></button>}

function SocialHome({data,onFriend,onAll}:{data:SocialData;onFriend:(friend:Friend)=>void;onAll:()=>void}){return <div className="social-home"><section className="social-section"><div className="social-section-head"><div><span>FRIENDS</span><h3>最近のフレンド</h3></div></div>{data.friends.length?<div className="native-friend-list">{data.friends.slice(0,3).map((friend)=><FriendRow key={friend.email} friend={friend} onOpen={()=>onFriend(friend)}/>)}</div>:<p className="social-empty boxed">フレンドはまだいません</p>}{data.friends.length>3?<button type="button" className="show-all-friends-button" onClick={onAll}>すべてのフレンドを見る</button>:null}</section></div>}

function FriendDetail({friend,ownCards,busy,onBack,onTrade,onRemove,onBlock}:{friend:Friend;ownCards:SharedCard[];busy:boolean;onBack:()=>void;onTrade:()=>void;onRemove:()=>void;onBlock:()=>void}){const [more,setMore]=useState(false);return <section className="native-subpage friend-profile"><header><button type="button" onClick={onBack}>‹ フレンド</button><button type="button" aria-label="その他の操作" onClick={()=>setMore(!more)}>•••</button>{more?<div className="friend-more-menu"><button type="button" onClick={onRemove}>フレンドを解除</button><button type="button" onClick={onBlock}>ブロック</button></div>:null}</header><div className="friend-profile-identity"><PersonAvatar person={friend}/><h2>{friend.displayName}</h2><p>{friend.cards.length} CARDS</p></div><Button disabled={busy||!friend.cards.length||!ownCards.length} onClick={onTrade}>トレードを提案</Button><div className="friend-profile-section"><span>所有カード</span><div className="friend-profile-grid">{friend.cards.map((card)=><MiniCard key={card.id} card={card}/>)}</div></div></section>}

function FriendRequests({data,busy,onAct,onNotice}:{data:SocialData;busy:boolean;onAct:(payload:Record<string,unknown>,message:string)=>void;onNotice:(message:string)=>void}){const [id,setId]=useState("");const [copied,setCopied]=useState(false);const incoming=data.people.filter((p)=>p.relationship==="incoming"),outgoing=data.people.filter((p)=>p.relationship==="outgoing");async function copy(){try{await navigator.clipboard.writeText(data.ownFriendId);setCopied(true);onNotice("フレンドIDをコピーしました");window.setTimeout(()=>setCopied(false),1600)}catch{onNotice("コピーできませんでした。IDを長押ししてコピーしてください")}}return <div className="requests-flow"><section className="social-section"><div className="social-section-head"><div><span>INCOMING</span><h3>受信した申請</h3></div><b>{incoming.length}</b></div>{incoming.length?<div className="people-list">{incoming.map((p)=><div className="person-row" key={p.email}><PersonAvatar person={p}/><strong>{p.displayName}</strong><div><Button variant="outline" disabled={busy} onClick={()=>onAct({action:"friend.decline",targetEmail:p.email},"申請を辞退しました")}>辞退</Button><Button disabled={busy} onClick={()=>onAct({action:"friend.accept",targetEmail:p.email},"フレンドになりました")}>承認</Button></div></div>)}</div>:<p className="social-empty">受信した申請はありません</p>}</section><section className="social-section"><div className="social-section-head"><div><span>SENT</span><h3>送信中</h3></div><b>{outgoing.length}</b></div>{outgoing.length?<div className="people-list">{outgoing.map((p)=><div className="person-row" key={p.email}><PersonAvatar person={p}/><strong>{p.displayName}</strong><Button variant="outline" disabled={busy} onClick={()=>onAct({action:"friend.remove",targetEmail:p.email},"フレンド申請を取り消しました")}>取消</Button></div>)}</div>:<p className="social-empty">送信中の申請はありません</p>}</section><section className="social-section friend-id-section"><div className="social-section-head"><div><span>FRIEND ID</span><h3>フレンドを追加</h3></div></div><div className="friend-id-form"><Input value={id} onChange={(e)=>setId(e.target.value.toUpperCase())} placeholder="PA-XXXXXXXX" maxLength={11}/><Button disabled={busy||!id.trim()} onClick={()=>{onAct({action:"friend.request",friendId:id.trim().toUpperCase()},"フレンド申請を送りました");setId("")}}>申請する</Button></div><div className="own-friend-id"><span>あなたのID</span><strong>{data.ownFriendId}</strong><Button variant="outline" onClick={()=>void copy()}>{copied?"✓ コピー済み":"コピー"}</Button></div></section></div>}

function TradeList({trades,busy,onAct,onAccept}:{trades:Trade[];busy:boolean;onAct:(payload:Record<string,unknown>,message:string)=>void;onAccept:(trade:Trade)=>void}){const pending=trades.filter((t)=>t.status==="pending"),history=trades.filter((t)=>t.status!=="pending").slice(0,10);return <div className="trade-home"><section className="social-section"><div className="social-section-head"><div><span>ACTIVE</span><h3>進行中</h3></div><b>{pending.length}</b></div>{pending.length?<div className="trade-list">{pending.map((trade)=>{const give=trade.direction==="incoming"?trade.requestedCard:trade.offeredCard,get=trade.direction==="incoming"?trade.offeredCard:trade.requestedCard;return <article className="trade-row" key={trade.id}><div className="trade-name"><span>{trade.direction==="incoming"?"受信":"送信中"}</span><strong>{trade.otherName}</strong></div><div className="trade-cards"><div><small>あなたが受け取る</small>{get?<MiniCard card={get}/>:null}</div><b>⇄</b><div><small>あなたが渡す</small>{give?<MiniCard card={give}/>:null}</div></div><div className="trade-actions">{trade.direction==="incoming"?<><Button variant="outline" disabled={busy} onClick={()=>onAct({action:"trade.decline",tradeId:trade.id},"交換申請を辞退しました")}>辞退</Button><Button disabled={busy} onClick={()=>onAccept(trade)}>内容を確認</Button></>:<Button variant="outline" disabled={busy} onClick={()=>onAct({action:"trade.cancel",tradeId:trade.id},"交換申請を取り消しました")}>取消</Button>}</div></article>})}</div>:<p className="social-empty boxed">進行中のトレードはありません</p>}</section>{history.length?<section className="social-section trade-history"><div className="social-section-head"><div><span>HISTORY</span><h3>履歴</h3></div></div>{history.map((trade)=><div key={trade.id}><span>{trade.otherName}</span><small>{trade.status==="accepted"?"成立":trade.status==="declined"?"辞退":"取消"}</small></div>)}</section>:null}</div>}

function CardPicker({title,cards,selected,onSelect}:{title:string;cards:SharedCard[];selected:string;onSelect:(id:string)=>void}){const [search,setSearch]=useState(""),[rarity,setRarity]=useState("ALL");const shown=cards.filter((card)=>(rarity==="ALL"||card.rarity===rarity)&&(!search||`${card.name} ${card.team} ${card.series}`.toLowerCase().includes(search.toLowerCase())));return <div className="trade-picker-step"><h2>{title}</h2><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="カードを検索"/><div className="trade-rarity-chips">{["ALL","CORE","RARE","ELITE","ICON"].map((item)=><button type="button" className={rarity===item?"is-active":""} key={item} onClick={()=>setRarity(item)}>{item}</button>)}</div><div className="trade-picker-grid">{shown.map((card)=><MiniCard key={card.id} card={card} selected={selected===card.id} onClick={()=>onSelect(card.id)}/>)}</div></div>}
function TradeComposer({friend,ownCards,busy,onBack,onSubmit}:{friend:Friend;ownCards:SharedCard[];busy:boolean;onBack:()=>void;onSubmit:(offer:SharedCard,request:SharedCard)=>void}){const [step,setStep]=useState(1),[offerId,setOfferId]=useState(""),[requestId,setRequestId]=useState("");const offer=ownCards.find((c)=>c.id===offerId),request=friend.cards.find((c)=>c.id===requestId);return <section className="native-subpage trade-composer"><header><button type="button" onClick={step===1?onBack:()=>setStep(step-1)}>‹ 戻る</button><span>STEP {step} / 3</span></header>{step===1?<CardPicker title="あなたが渡すカードを選ぶ" cards={ownCards} selected={offerId} onSelect={setOfferId}/>:step===2?<CardPicker title="受け取りたいカードを選ぶ" cards={friend.cards} selected={requestId} onSelect={setRequestId}/>:<div className="trade-review"><p className="section-kicker">TRADE REVIEW</p><h2>トレード確認</h2><section><span>あなたが渡す</span>{offer?<MiniCard card={offer}/>:null}</section><b>⇅</b><section><span>あなたが受け取る</span>{request?<MiniCard card={request}/>:null}</section><p>{friend.displayName}さんへ送信します</p></div>}<Button className="subpage-primary" disabled={busy||(step===1&&!offer)||(step===2&&!request)} onClick={()=>step<3?setStep(step+1):offer&&request&&onSubmit(offer,request)}>{step===3?`${friend.displayName}さんに提案する`:"次へ"}</Button></section>}
export default function SocialPanel({ownCards,onNotice,onCollectionChanged,onSubpageChange,initialView="friends"}:{ownCards:SharedCard[];onNotice:(message:string)=>void;onCollectionChanged:()=>void;onSubpageChange?:(open:boolean)=>void;initialView?:"friends"|"requests"|"trades"}){const [data,setData]=useState<SocialData|null>(null),[busy,setBusy]=useState(false),[view,setView]=useState<"friends"|"requests"|"trades">(initialView),[friend,setFriend]=useState<Friend|null>(null),[all,setAll]=useState(false),[tradeFriend,setTradeFriend]=useState<Friend|null>(null),[remove,setRemove]=useState<Friend|null>(null),[blocked,setBlocked]=useState<Friend|null>(null),[accept,setAccept]=useState<Trade|null>(null);
const load=useCallback(async()=>{const response=await fetch("/api/social",{cache:"no-store"}),result=await response.json();if(response.ok)setData(result);else onNotice(result.error??"フレンド情報を読み込めませんでした")},[onNotice]);useEffect(()=>{const controller=new AbortController();void fetch("/api/social",{cache:"no-store",signal:controller.signal}).then(async(response)=>{const result=await response.json();if(response.ok)setData(result);else onNotice(result.error??"フレンド情報を読み込めませんでした")});return()=>controller.abort()},[onNotice]);const subpage=Boolean(friend||all||tradeFriend);useEffect(()=>onSubpageChange?.(subpage),[subpage,onSubpageChange]);
async function act(payload:Record<string,unknown>,message:string,changed=false){setBusy(true);try{const response=await fetch("/api/social",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)onNotice(result.error??"操作を完了できませんでした");else{onNotice(message);await load();if(changed)onCollectionChanged()}return response.ok}catch{onNotice("通信に失敗しました。もう一度お試しください");return false}finally{setBusy(false)}}
async function safetyAction(action:"block"|"unblock",targetEmail:string){setBusy(true);try{const response=await fetch("/api/safety",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({ action,targetEmail })}),result=await response.json();if(!response.ok)onNotice(result.error??"操作を完了できませんでした");else{onNotice(action==="block"?"参加者をブロックしました":"ブロックを解除しました");setFriend(null);await load()}}finally{setBusy(false)}}async function block(){if(!blocked)return;await safetyAction("block",blocked.email);setBlocked(null)}
if(!data)return <section className="social-loading">フレンド情報を読み込んでいます</section>;if(friend)return <FriendDetail friend={friend} ownCards={ownCards} busy={busy} onBack={()=>setFriend(null)} onTrade={()=>setTradeFriend(friend)} onRemove={()=>setRemove(friend)} onBlock={()=>setBlocked(friend)}/>;if(all)return <section className="native-subpage friend-directory-page"><header><button type="button" onClick={()=>setAll(false)}>‹ フレンド</button></header><h2>すべてのフレンド</h2><div className="native-friend-list">{data.friends.map((f)=><FriendRow key={f.email} friend={f} onOpen={()=>setFriend(f)}/>)}</div></section>;if(tradeFriend)return <TradeComposer friend={tradeFriend} ownCards={ownCards} busy={busy} onBack={()=>setTradeFriend(null)} onSubmit={(offer,request)=>void act({action:"trade.create",targetEmail:tradeFriend.email,offeredCardId:offer.id,requestedCardId:request.id},"交換申請を送りました").then((ok)=>ok&&setTradeFriend(null))}/>;
const requestCount=data.people.filter((p)=>p.relationship==="incoming"||p.relationship==="outgoing").length,pending=data.trades.filter((t)=>t.status==="pending").length;return <div className="social-page"><section className="network-title social-title"><p className="section-kicker">FRIENDS & TRADES</p><h2>フレンド</h2></section><nav className="social-subnav">{([{id:"friends",label:"フレンド",count:data.friends.length},{id:"requests",label:"申請",count:requestCount},{id:"trades",label:"トレード",count:pending}] as const).map((x)=><button type="button" key={x.id} className={view===x.id?"is-active":""} onClick={()=>setView(x.id)}><span>{x.label}</span><b>{x.count}</b></button>)}</nav>{view==="friends"?<SocialHome data={data} onFriend={setFriend} onAll={()=>setAll(true)}/>:view==="requests"?<FriendRequests data={data} busy={busy} onAct={(p,m)=>void act(p,m)} onNotice={onNotice}/>:<TradeList trades={data.trades} busy={busy} onAct={(p,m)=>void act(p,m)} onAccept={setAccept}/>}<AlertDialog open={Boolean(remove)} onOpenChange={(open)=>!open&&setRemove(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>フレンドを解除しますか？</AlertDialogTitle><AlertDialogDescription>進行中のトレード申請も取り消されます。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>戻る</AlertDialogCancel><AlertDialogAction onClick={()=>{if(remove)void act({action:"friend.remove",targetEmail:remove.email},"フレンドを解除しました");setRemove(null);setFriend(null)}}>解除する</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><AlertDialog open={Boolean(blocked)} onOpenChange={(open)=>!open&&setBlocked(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>この参加者をブロックしますか？</AlertDialogTitle><AlertDialogDescription>フレンド登録が解除され、進行中のトレードも取り消されます。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>戻る</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>void block()}>ブロック</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><AlertDialog open={Boolean(accept)} onOpenChange={(open)=>!open&&setAccept(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>このトレードを成立させますか？</AlertDialogTitle><AlertDialogDescription>成立後は取り消せません。</AlertDialogDescription></AlertDialogHeader>{accept?<div className="accept-trade-summary"><div><span>あなたが渡す</span>{accept.requestedCard?<MiniCard card={accept.requestedCard}/>:null}</div><b>⇅</b><div><span>あなたが受け取る</span>{accept.offeredCard?<MiniCard card={accept.offeredCard}/>:null}</div></div>:null}<AlertDialogFooter><AlertDialogCancel>戻る</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={()=>{if(accept)void act({action:"trade.accept",tradeId:accept.id},"✓ TRADE COMPLETE — カードを交換しました",true);setAccept(null)}}>交換を確定</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>}
